buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.wisepersist:gwt-gradle-plugin:1.1.16'
        classpath 'org.gretty:gretty:4.0.3'
    }
}

plugins {
    id 'war'
}

apply plugin: 'gwt'
apply plugin: 'org.gretty'

def gdxVersion = '1.12.1'
def gwtVersion = '2.10.0'

gwt {
    gwtVersion = gwtVersion
    maxHeapSize = '1G'
    minHeapSize = '1G'

    src = files(file('src/main/java'))
    // Include core Kotlin sources for GWT compilation
    src += files(project(':core').file('src/main/kotlin'))

    modules 'com.aurora.reading.GdxDefinition'

    compiler {
        strict = true
        disableCastChecking = true
    }
}

dependencies {
    implementation project(':core')

    // GWT SDK
    implementation "org.gwtproject:gwt-user:$gwtVersion"
    implementation "org.gwtproject:gwt-dev:$gwtVersion"

    // libGDX GWT backend
    implementation "com.badlogicgames.gdx:gdx:$gdxVersion:sources"
    implementation "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion:sources"

    // Box2D for GWT
    implementation "com.badlogicgames.gdx:gdx-box2d:$gdxVersion:sources"
    implementation "com.badlogicgames.gdx:gdx-box2d-gwt:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-box2d-gwt:$gdxVersion:sources"

    // Note: FreeType is NOT available for GWT
    // FontManager will need to use BitmapFont instead in web version
}

task dist(dependsOn: ['clean', 'compileGwt']) {
    doLast {
        copy {
            from 'build/gwt/out'
            into 'build/dist'
        }
        copy {
            from 'webapp'
            into 'build/dist'
        }
    }
}

gretty {
    httpPort = 8080
    contextPath = '/'
    servletContainer = 'jetty11'
}
